### ISSUE TITLE
Assignment glitch

### ISSUE THREAD

**Issue by Golden-Piglin** [zSnout/kama-sona#2]
### Describe the bug

whenever i try to see my issignments it breaks and sends me to the login screen

### To reproduce

click assignments

### Expected behavior

boots you to login screen

### What browsers are you seeing the problem on?

Chrome

**Comment by zsakowitz** [comment]
Hey @Golden-Piglin!

Thanks for submitting this issue. I've been working to fix it, and I think it should be fixed with b95bc95. On your end, please verify the bug no longer exists and reply letting me know the status.

**Comment by zsakowitz** [comment]
I also believe some of your bug report is incorrect. Are you sure the expected behavior is "boots you to the login screen?" In the future, double check your bug report before submitting them.

**Comment by WattyDatGod** [comment]
OK
