### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WattyDatGod** [zSnout/kama-sona#6]
### Describe the bug

yeah its an eerror

### What error message appears?

500 | Invalid `prisma.resource.create()` invocation:Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneResource.data.ResourceCreateInput.viewableAfter`: Error parsing value: Invalid DateTime: '+023123-01-16T00:00:00.000Z' (must be ISO 8601 compatible). Underlying error: input contains invalid characters., Query parsing/validation error at `Mutation.createOneResource.data.ResourceUncheckedCreateInput.categoryId`: A value is required but not set.]` at `Mutation.createOneResource.data`

### To reproduce

i forgoted

### Expected behavior

agression

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari, Microsoft Edge, Node.JS, Other

### What operating systems are you seeing the problem on?

MacOS, Windows, Linux, iOS / iPadOS, Android, ChromeOS, Other

**Comment by zsakowitz** [comment]
This is a result of allowing extremely large dates in the date pickers. As a temporary fix, we've limited all date picker to a maximum of December 31, 9999. We'll revisit this in about eight thousand years.
